# Generated by Django 5.1.1 on 2024-10-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoClimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidade', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField()),
                ('temperatura', models.FloatField()),
                ('sensacao_termica', models.FloatField()),
                ('umidade', models.FloatField()),
                ('condicao_climatica', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('endereco_resolvido', models.CharField(max_length=200)),
            ],
        ),
    ]
